### **Задание на повторение материала

#### Задание 1
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [14]:
import numpy as np
%config Completer.use_jedi = False 

In [15]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### Задание 2
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [21]:
a1 = a.reshape(2, 6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [22]:
a2 = a.reshape(3, 4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
a3 = a.reshape(4, 3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [35]:
a4 = a.reshape(12, 1)
a4

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [37]:
a5 = a.reshape(6, 2)
a5

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

#### Задание 3

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [38]:
a1 = a.reshape(2, -1)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [39]:
a2 = a.reshape(3, -1)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [40]:
a3 = a.reshape(4, -1)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [41]:
a4 = a.reshape(-1, 12)
a4

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [43]:
a5 = a.reshape(-1, 6)
a5

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

#### Задание 4
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


In [45]:
print('Нет') 

Нет


#### Задание 5

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.



In [46]:
x = np.random.randn(3, 4)
x

array([[ 0.53958007, -0.44937589, -0.7610179 ,  1.83432817],
       [-1.48624854, -0.54305287,  0.01332773, -0.77806527],
       [-1.08763656, -0.68715378,  1.03770705, -0.03060487]])

In [48]:
y = x.reshape(1, -1)
y

array([[ 0.53958007, -0.44937589, -0.7610179 ,  1.83432817, -1.48624854,
        -0.54305287,  0.01332773, -0.77806527, -1.08763656, -0.68715378,
         1.03770705, -0.03060487]])

#### Задание 6

Создать массив aч, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.



In [50]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### Задание 7

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?



In [51]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [57]:
print('Отличаются числом осей') 

Отличаются числом осей


#### Задание 8

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.



In [59]:
a = np.zeros((2, 2))
b = np.ones((3,2))
a,b

(array([[0., 0.],
        [0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]))

In [65]:
v = np.vstack((a, b))
v.size

10

#### Задание 9

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?




In [67]:
a=np.arange(0, 12) 
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [68]:
A=a.reshape(4,3) 
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [70]:
B = np.dot(A, At) 
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [72]:
B.shape

(4, 4)

In [74]:
B_inverted = np.linalg.inv(B)
B_inverted

# LinAlgError("Singular matrix")- матрица сингулярная, вычеслить обратную матрицу для матрицы B - нельзя.

LinAlgError: Singular matrix

#### Задание 10
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.


In [75]:
np.random.seed(42)

#### Задание 11
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 



In [76]:
c=np.random.randint(0, 16,16) 
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

#### Задание 12

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [77]:
C=c.reshape(4,4) 
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [78]:
D = B+C*10
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

D_inv=np.linalg.inv(D) 
D_inv

In [80]:
d=np.linalg.det(D)
d

-28511999.999999944

In [81]:
r = np.linalg.matrix_rank(D) 
r

4

#### Задание 13

13.1 Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
Убедитесь, что в матрице D_inv остались только нули и единицы

13.2 С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

#### Задание 13.1

In [84]:
D_inv = np.where(D_inv<0, 0,1)
D_inv

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

#### Задание 13.2

In [85]:
E=np.where(D_inv==1, B, C) 
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])